### ISSUE TITLE
glTFTranslator.py  not showing up in plugin manager

### ISSUE THREAD

**Issue by jinshim** [matiascodesal/maya-glTF#10]
glTFTranslator.py is  not showing up in plugin manager.
I placed everything in right directory but still this is not working...

Windows10, Maya2017

**Comment by matiascodesal** [comment]
Hi @jinshim!  Are you maybe using Maya LT?  That version won't work.

If that's not the case, then could you provide the full paths to where you copied the files to so we can verify that is correct? You can omit your username if you like.  

Also, have you checked out? https://github.com/WonderMediaProductions/Maya2glTF It has more features and fortunately has a release build that should work for you.

**Comment by matiascodesal** [comment]
Going close this.  Please let me know if it turns out this is not a Maya LT compatibility issue.
