### ISSUE TITLE
Exporting Transparency

### ISSUE THREAD

**Issue by Miikka61** [matiascodesal/maya-glTF#13]
Hello,

Im probably doing something wrong, but I cant get anything to export with any trans values. Any help would be much appreciated.

**Comment by matiascodesal** [comment]
This seemed to be working before, but I'm now explicitly setting the alphaMode property on the material and it seems to be working again on some of the viewers that I tested.

@Miikka61, I've merged the fix in.  Please download the latest from this repo.  Let me know if you run into any issue or have any questions.
