### ISSUE TITLE
Error loading plugin in MayaLT 2020

### ISSUE THREAD

**Issue by patrickmatte** [matiascodesal/maya-glTF#16]
This is the error I get every time i try to load the plugin.

// Error: file: /Applications/Autodesk/mayaLT2020/Maya.app/Contents/scripts/others/pluginWin.mel line 317: Plug-in, "/Users/Shared/Autodesk/maya/2020LT/plug-ins/glTFExport.py", was not found on MAYA_PLUG_IN_PATH. //

**Comment by matiascodesal** [comment]
It should be `glTFTranslator.py` that goes in the plug-in directory.  In any case, I don't think Maya LT supports custom plugins:
https://knowledge.autodesk.com/support/maya-lt/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/MayaLT-CustomizingMayaLT/files/GUID-6613719F-FDFD-416A-AD7A-8DFEF6B4DEC8-htm.html
