### ISSUE TITLE
Plugin not compatible with Maya 2018

### ISSUE THREAD

**Issue by Yugloocamai** [matiascodesal/maya-glTF#8]
Could we make it compatible with the latest version of Maya?
`
// Warning: file: /Applications/Autodesk/maya2018/Maya.app/Contents/scripts/others/pluginWin.mel line 909: No initializePlugin() or initializePlugin2() function
 // 
// Error: file: /Applications/Autodesk/maya2018/Maya.app/Contents/scripts/others/pluginWin.mel line 909:  (glTFExport)
`

**Comment by Yugloocamai** [comment]
I was trying to load the plugin directly in the plugins manager, from the wrong install path...

**Comment by matiascodesal** [comment]
@Yugloocamai No worries.  Glad you got it.
