### ISSUE TITLE
"Error: line 0: Could not save file"

### ISSUE THREAD

**Issue by b-ran-don** [matiascodesal/maya-glTF#9]
Hello, I'm having an issue not being able to export out of Maya. This is the error I'm getting:

// Error: line 0: IndexError: file C:/Users/Brandon/Documents/maya/2018/scripts\glTFExport.py line 397: list index out of range // 
// Error: line 0: Could not save file "C:/Users/Brandon/Desktop/anmRig_combined.glb". //

Any idea why I'm getting this error?

Thanks!
Brandon

**Comment by matiascodesal** [comment]
Hi @b-ran-don!  Is it possible that you're exporting a mesh without any material assigned?

**Comment by b-ran-don** [comment]
Hey @matiascodesal . So sorry to have missed your first reply. Somehow it didn't catch my attention. It was exported with a material assigned. Are these the two type of nodes you are talking about? If so those are normal and are part of the modeling side of things rather than rigging.
![capturegltf](https://user-images.githubusercontent.com/33333076/47184494-aace8000-d2df-11e8-891f-e5fce8304c9b.JPG)

**Comment by Kendero** [comment]
Hello! i have some problems. and i dont know how i can fix it

# Warning: No objects specified that can have connections. # 
# Failed to write file information
// Error: line 0: IndexError: file C:/Users/Kendero/Documents/maya/2017/scripts\glTFExport.py line 399: list index out of range // 
// Error: line 0: Could not save file "D:/Work/work/3D_projects/cat/catExp.glb". //

**Comment by matiascodesal** [comment]
@b-ran-don and @Kendero Would one of you be able to share a simple scene for be debug?

**Comment by westomopresto** [comment]
I'm also having this same issue. I've attached my maya scene, this happens even with no materials assigned.

[stoker_walk.zip](https://github.com/matiascodesal/maya-glTF/files/3423988/stoker_walk.zip)

**Comment by matiascodesal** [comment]
Much appreciated @westomopresto!  I found that I needed to skip exporting intermediateObjects.  Please re-download the plugin to get the fix.  Closing this issue.  Feel free to open another issue if you encounter any more problems.

**Comment by volkanongun** [comment]
after many tries, Maya keeps crashing when i try to export glTF file format by selecting whole scene export. Mac os mojave, maya 2018 and i applied all steps of the small tutorial in the README. also checked for non-material assigned meshes and found 0. is there another fix for this?

**Comment by oninross** [comment]
@volkanongun I opened up another ticket.  Might be related to it.  See #17
